### ISSUE TITLE
CyIpopt version 1.0.0 release checklist

### ISSUE THREAD

**Issue by brocksam** [mechmotum/cyipopt#94]
Things to do before version 1.0.0 release. Please comment suggestions for other items to add.

- [x] Decide which currently-open issues should be address for this release.
- [x] Fix CI failure associated with PR #86 (finish standardising the new PEP8-compliant API).
- [x] Merge PR #86.
- [x] Edit docs (and README) to reflect version 1.0.0 new PEP8-compliant API and new windows installation options.
- [x] Ensure CHANGELOG is up-to-date.
- [x] Ensure docs are up-to-date.
- [x] Ensure CI is passing.
- [ ] Switch from the pypi ipopt package name to cyipopt
- [x] Add page in documentation showing use of the scipy interface

P.S. @moorepants please feel free to move this to a milestone so that we can link issues/PRs if you think that's a better approach (I can't as I don't have privileges).

**Comment by moorepants** [comment]
I can make a milestone for this.

**Comment by moorepants** [comment]
I can also give you more permissions!

**Comment by moorepants** [comment]
I gave you maintain permissions. My only request is that changes go through PRs and at least one other person with relevant familiarity with the code has approved it. So far it seems you have more discipline with best practices, so I'm sure it goes without saying :)

**Comment by brocksam** [comment]
> I gave you maintain permissions. 

Thanks!

> My only request is that changes go through PRs and at least one other person with relevant familiarity with the code has approved it. So far it seems you have more discipline with best practices, so I'm sure it goes without saying :)

Completely agree, will make sure all changes go through PR and review process :)

**Comment by moorepants** [comment]
>  Decide which currently-open issues should be address for this release.

I don't think we need to address any of the other issues for the release.

>  Edit docs (and README) to reflect version 1.0.0 new PEP8-compliant API and new windows installation options.

I think this should be done.

**Comment by moorepants** [comment]
For:

> Switch from the pypi ipopt package name to cyipopt

I'm wondering the best way to handle this. I can push to the new pypi distribution name (cyipopt) but I should also push maybe a 0.3.1 to the name ipopt with a large warning in the README pointing to the new name. We could also leave it be too. Or push to both names.

**Comment by brocksam** [comment]
> > Decide which currently-open issues should be address for this release.
> 
> I don't think we need to address any of the other issues for the release.

Agreed.

> > Edit docs (and README) to reflect version 1.0.0 new PEP8-compliant API and new windows installation options.
> 
> I think this should be done.

I've had a quick skim through the updated docs (thanks very much for doing this!) and can't see anything glaring that still needs updating. So I agree this is done.

> For:
>
> > Switch from the pypi ipopt package name to cyipopt
> 
> I'm wondering the best way to handle this. I can push to the new pypi distribution name (cyipopt) but I should also push maybe a 0.3.1 to the name ipopt with a large warning in the README pointing to the new name. We could also leave it be too. Or push to both names.

I think we should only push 1.X.X to cyipopt on PyPI. We are deprecating references to the old "ipopt" in the package so should also do the same where it is hosted. It makes sense to me to stop using https://pypi.org/project/ipopt/ in favour of https://pypi.org/project/cyipopt/ at the same time as changing the package name to cyipopt. A 0.3.1 release on https://pypi.org/project/ipopt/ making it clear that that'll be the last release under that project name, but that 1.X.X is available at https://pypi.org/project/cyipopt/ makes the most sense to me.

**Comment by moorepants** [comment]
Sounds good. I'll work on making the release.

**Comment by moorepants** [comment]
On twine upload I'm getting:

```
moorepants@nandi:cyipopt(master)$ twine upload dist/cyipopt-1.0.1.tar.gz 
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: moorepants
Enter your password: 
Uploading cyipopt-1.0.1.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.6k/47.6k [00:01<00:00, 35.6kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'cyipopt' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

But there is nothing at: https://pypi.org/project/cyipopt/

**Comment by brocksam** [comment]
> On twine upload I'm getting:
> 
> ```
> moorepants@nandi:cyipopt(master)$ twine upload dist/cyipopt-1.0.1.tar.gz 
> Uploading distributions to https://upload.pypi.org/legacy/
> Enter your username: moorepants
> Enter your password: 
> Uploading cyipopt-1.0.1.tar.gz
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.6k/47.6k [00:01<00:00, 35.6kB/s]
> NOTE: Try --verbose to see response content.
> HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
> The name 'cyipopt' isn't allowed. See https://pypi.org/help/#project-name for more information.
> ```
> 
> But there is nothing at: https://pypi.org/project/cyipopt/

https://pypi.org/help/#project-name says "The project name has been registered by another user, but no releases have been created." But I agree, it doesn't look like there's anything on PyPI under "cyipopt" so I'm currently confused too...

**Comment by moorepants** [comment]
I would think if it was registered it would show a page with no releases. I could try requesting the name via the github repo issue tracker they link.

**Comment by bocklund** [comment]
Looks like this might be the way to request it https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME

**Comment by moorepants** [comment]
I just did this: https://github.com/pypa/pypi-support/issues/1008

**Comment by moorepants** [comment]
I'm not sure how long a name change would take (if granted). So I'm thinking we should just push to pypi ipopt for now. We can migrate the pypi name anytime, it doesn't have to be with this particular version.

**Comment by moorepants** [comment]
I pushed the release to ipopt on pypi: https://pypi.org/project/ipopt/1.0.3/

**Comment by moorepants** [comment]
Gonna call this closed. We can open a new issue for the pypi name change.

**Comment by moorepants** [comment]
Thanks for all the work on this! It's live on pypi and anaconda.org.

**Comment by brocksam** [comment]
Thanks @moorepants for your work getting the release out!
